# Simple NumPy Test

In [1]:
from numpy import *

## 数据类型
numpy中提供两种不同的数据类型,array和matrix,二者数学运算方式有所不同

In [2]:
randArray = random.rand(4,4)
randArray

array([[0.54086119, 0.46367117, 0.24242012, 0.4788656 ],
       [0.28019174, 0.27478699, 0.35500738, 0.12827488],
       [0.16359084, 0.51270133, 0.49518044, 0.72836616],
       [0.45200996, 0.52879062, 0.57064944, 0.50138251]])

In [4]:
randMat = mat(randArray)
randMat

matrix([[0.54086119, 0.46367117, 0.24242012, 0.4788656 ],
        [0.28019174, 0.27478699, 0.35500738, 0.12827488],
        [0.16359084, 0.51270133, 0.49518044, 0.72836616],
        [0.45200996, 0.52879062, 0.57064944, 0.50138251]])

## 矩阵求逆


In [13]:
invRandMat = randMat.I
invRandMat

matrix([[ -1.27569102, -11.85706652,  -6.26771719,  13.35715011],
        [  8.98636521,  34.6632819 ,  13.55774061, -37.14666673],
        [ -4.99344103,  -9.01609721,  -4.11442791,  13.0529802 ],
        [ -2.64424108, -15.60699683,  -3.96551416,  14.2736692 ]])

In [9]:
randMat*invRandMat

matrix([[ 1.00000000e+00,  1.77635684e-15,  8.88178420e-16,
          0.00000000e+00],
        [-4.44089210e-16,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 4.44089210e-16,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -1.77635684e-15,  0.00000000e+00,
          1.00000000e+00]])

实际上,这里应该是单位矩阵,然而由于计算机计算误差,因此实际输出非对角线元素只是尽可能小

我们可以计算产生的误差

In [12]:
myEye = randMat*invRandMat
myEye - eye(4)

matrix([[ 2.22044605e-16,  1.77635684e-15,  8.88178420e-16,
          0.00000000e+00],
        [-4.44089210e-16, -8.88178420e-16,  0.00000000e+00,
          0.00000000e+00],
        [ 4.44089210e-16,  0.00000000e+00,  4.44089210e-16,
          0.00000000e+00],
        [ 0.00000000e+00, -1.77635684e-15,  0.00000000e+00,
          1.77635684e-15]])